### ISSUE TITLE
Combining this code with Waifu2x

### ISSUE THREAD

**Issue by DonaldTsang** [deeppomf/DeepMindBreak#14]
Which one could yield better results?
- Censored Compressed Image => Waifu2x => DeepMindBreak => Pure Image
- Censored Compressed Image => DeepMindBreak => Waifu2x => Pure Image

see: https://github.com/nagadomi/waifu2x

**Comment by deeppomf** [comment]
waifu2x is outdated, but super resolution could be used with DeepMindBreak.
I'll think about it.
Finishing DeepMindBreak V2 comes first.

**Comment by DonaldTsang** [comment]
@deeppomf Could it be possible to make a benchmark between Waifu2x and other super-res project once DBMv2 is done? https://github.com/nagadomi/waifu2x/issues/251

**Comment by Kadantte** [comment]
Waifu2x it's a long time not Updated , i hope they Updated even it's still working great but not that much xD

**Comment by DonaldTsang** [comment]
@Kadantte considering https://github.com/nagadomi/waifu2x/issues/251 I think they are getting "weaker" when compared with others

**Comment by Kadantte** [comment]
For me i don't anything like Waifu2x i'll look for something better than it ...

**Comment by lllyasviel** [comment]
Dull. Waifu2x is not weak at all. If you try other so called "better" method, you will find that their performance is just similar to Waifu2x, and their time consuming is much longer. Stop talking and try yourself.

**Comment by DonaldTsang** [comment]
@lllyasviel I am not trying to insult, but their refusal to update benchmarks with new architectures sure makes me think.

**Comment by deeppomf** [comment]
@lllyasviel That might be the case. All the newest methods are trained and tested on real world images and never on anime images. Like you said, I'll have to try it myself.
