### ISSUE TITLE
ValueError: Cannot feed value of shape

### ISSUE THREAD

**Issue by kaikun97** [deeppomf/DeepMindBreak#2]
First of all please excuse me, I am relatively new to python.

Getting this error when trying to train data.

`ValueError: Cannot feed value of shape (1, 128, 128, 4) for Tensor 'Placeholder:0', which has shape '(16, 128, 128, 3)'`

It seems to not like my training images even though I have made them 128x128 and are in .png format

Would it be possible to provide more detailed information on what specific requirements are for training images to work with this tool and the steps needed to prepare the training data (are one of each, censored and censored needed or can they be done as a batch? And do the censor lines also need to be green like the de-censor process?)

**Comment by deeppomf** [comment]
Images with shape (1, 128, 128, 4) have a transparency channel. I will change it so images with a transparency channel can be used for training.
I'll explain the training data format in greater detail.

**Comment by kaikun97** [comment]
Okay thank you, in that case i'll remove the transparency channel from the training data for now.

**Comment by kaikun97** [comment]
I removed transparency and it didn't work. I also tried converting the images into BMP which doesn't support transparency and then back into PNG but it still doesn't work. Both times this same error is the result:

`ValueError: Cannot feed value of shape (1, 128, 128, 4) for Tensor 'Placeholder:0', which has shape '(16, 128, 128, 3)'`

**Comment by deeppomf** [comment]
Should be fixed in 57932e1

**Comment by kaikun97** [comment]
Has not changed anything, even after converting with updated to_npy.py

I have sent an email about discord, perhaps I can provide the data I am using for you to debug with.

**Comment by deeppomf** [comment]
I've responded to your email. Send me the data when you can.
