### ISSUE TITLE
mask_batch not defined in train.py

### ISSUE THREAD

**Issue by kaikun97** [deeppomf/DeepMindBreak#3]
First of all please excuse me, I am relatively new to python.

Attempting to train gives this error:

`Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train()
  File "train.py", line 111, in train
    completion = sess.run(model.completion, feed_dict={x: x_batch, mask: mask_batch, is_training: False})
UnboundLocalError: local variable 'mask_batch' referenced before assignment`

This happens when I get my 128x128 training data .png files and convert to .npy and then start the training.

**Comment by kaikun97** [comment]
Reopened, it seems mask_batch is supposed to be defined in train.py, only runs after I define it.

**Comment by deeppomf** [comment]
Do you have the latest version of the code? I can't replicate that issue.

**Comment by kaikun97** [comment]
I did and some other people involved in python coding told me the core issue is that mask_batch isn't defined in the first place and I can't see it defined as a variable first anywhere in the code, only references to it.

**Comment by deeppomf** [comment]
I initialized mask_batch outside the loop. Should be good now.
