### ISSUE TITLE
Have you tried deep image prior?

### ISSUE THREAD

**Issue by AtlantixJJ** [deeppomf/DeepMindBreak#4]
First of all, well, a pretty impressive repo...

Please refer to the inpainting examples in https://github.com/DmitryUlyanov/deep-image-prior. It seems that their techniques are better than the image pair shown in this repo. Have you tried this out? By the way, I think the implementation would be quite simple.

**Comment by deeppomf** [comment]
Deep Image Prior will likely not work for hentai decensoring. From the paper: "Being non-trainable, our method  is not expected to work correctly for “highly-semantical” large-hole inpainting (e.g. face inpainting)."
Thanks for the heads up though!
