### ISSUE TITLE
[Solved] 0it [00:00, ?it/s] No output

### ISSUE THREAD

**Issue by 1004100** [deeppomf/DeepMindBreak#5]
Hello!

I run decensor.py using Python 3.6 but there was no output file, only the folder was created.

What could the issue be?

**Comment by 1004100** [comment]
I solve this problem by renaming "decensor_input_images" folder to just "decensor_input".

**Comment by deeppomf** [comment]
I'll fix the read me instructions. Thanks for reporting the issue!
